= Query executor

A small application to run queries against a database.

== JVM-Mode

=== Application
.Building the application
[source, bash]
----
./mvnw --define build-container-image clean verify
----

=== Starting the environment and testing the application
.Starting the image
[source, bash]
----
docker-compose \
  --file local-deployment/docker-compose.yml \
  --profile serivce \
  up \
  --detach
----

To test the application, execute

.Execute query `SELECT 1=1;`
[source, bash]
----
$ curl \
  'http://localhost:8080/run-query?query=SELECT%201%3D1%3B' \
  --verbose
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /run-query?query=SELECT%201%3D1%3B HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 0
<
* Connection #0 to host localhost left intact

----

The status-code will be `200`, indicating the query executed successfully. If a query fails, the status code will be `400`.

=== Stopping the environment
.Stopping the container
[source, bash]
----
docker-compose \
  --file local-deployment/docker-compose.yml \
  --profile service \
  down
----

== Native mode

=== Application
.Build a container image
[source, bash]
----
./mvnw \
  --define native \
  --define build-container-image \
  clean package
----
The resulting image will be named `de.turing85/run-query:latest` and `de.turing85/run-query:native`

=== Starting the environment and testing the application
.Starting the image
[source, bash]
----
docker-compose \
  --file local-deployment/docker-compose.yml \
  --profile native-serivce \
  up \
  --detach
----

To test the application, execute

.Execute query `SELECT 1=1;`
[source, bash]
----
$ curl \
  'http://localhost:8080/run-query?query=SELECT%201%3D1%3B' \
  --verbose
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /run-query?query=SELECT%201%3D1%3B HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 0
<
* Connection #0 to host localhost left intact

----

The status-code will be `200`, indicating the query executed successfully. If a query fails, the status code will be `400`.

=== Stopping the environment
.Stopping the container
[source, bash]
----
docker-compose \
  --file local-deployment/docker-compose.yml \
  --profile native-service \
  down
----

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://turing85.github.io"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#doc-turing85" title="Documentation">📖</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++