ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2026-01-25@sha256:e4d9d9e93603827d965e3aa2735ab251aa5b79da262af7fb7ef061bc39f327ff"

FROM ${DISTROLESS_IMAGE} AS runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
COPY \
  --chmod=111 \
   target/*-runner ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]