name: Populate Cache

description: |
  An action to populate the maven cache.

inputs:
  graalvm-distribution:
    description: The distribution of GraalVM to use
    default: mandrel
    required: true
  graalvm-version:
    description: The version of the GraalVM distribution to use
    default: 22.3.1-Final
    required: true
  java-version:
    description: The Java version to use
    default: '17'
    required: true
  nvd-api-key:
    description: The API key for the NVD database, used by the dependency-check scan plugin
    required: true


runs:
  using: composite

  steps:
    - name: Set up ${{ inputs.graalvm-distribution }} ${{ inputs.graalvm-version }} (Java ${{ inputs.java-version }})
      uses: graalvm/setup-graalvm@v1
      with:
        cache: 'maven'
        distribution: ${{ inputs.graalvm-distribution }}
        java-version: ${{ inputs.java-version }}
        version: ${{ inputs.graalvm-version }}
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define ci-populate-cache \
          --define nvdApiKey=${{ inputs.nvd-api-key }} \
          verify \
          quarkus:go-offline \
          de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3