name: Nightly CVE Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  GRAALVM_DISTRIBUTION: mandrel
  GRAALVM_VERSION: mandrel-22.3.2.1-Final
  JAVA_VERSION: 17

permissions:
  actions: write
  checks: write

jobs:
  populate-cache:
    name: Populate Cache
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Populate Cache
        uses: ./.github/actions/populate-cache
        with:
          graalvm-distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          graalvm-version: ${{ env.GRAALVM_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}

  owasp:
    name: OWASP Scan
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: OWASP Scan
        uses: ./.github/actions/owasp-scan
        with:
          download-artifacts: false
          graalvm-distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          graalvm-version: ${{ env.GRAALVM_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}